[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
dblik = "EE4v8mDaBcnXjYakNPUExR1DGZXS4ba4vyBSrqXXRRF3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = '/mnt/c/Users/Karol/.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
