[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
dblik = "EE4v8mDaBcnXjYakNPUExR1DGZXS4ba4vyBSrqXXRRF3"
experiments = "7Vo3RPXvCm7BNgUeHHdYmvMSUUvaWWpyQ6MjiJrpfgFy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = '/mnt/c/Users/Karol/.config/solana/id.json'

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/experiments.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/manual.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/dblik.ts"